<?php

namespace App\Constants;

class MsgCode
{
    const SUCCESS = 'SUCCESS';
    const VALIDATION_ERROR = 'VALIDATION_ERROR';
    const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    const LOGIN_FAILED = 'LOGIN_FAILED';
    const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
    const REGISTER_FAILED = 'REGISTER_FAILED';
    const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
    const USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS';
    const UNAUTHORIZED = 'UNAUTHORIZED';
    const FORBIDDEN = 'FORBIDDEN';
    const NOT_FOUND = 'NOT_FOUND';
    const SERVER_ERROR = 'SERVER_ERROR';
    const BAD_REQUEST = 'BAD_REQUEST';
}
